#!/usr/bin/env php
<?php
//脚本执行入口
// 定义项目路径

define('ROOT', __DIR__ . '/');

define('APP_PATH', ROOT . 'app/');

define('RUNTIME_PATH', ROOT . 'data/runtime/');

define('MODULE', 'console');

define('LOG_PATH', RUNTIME_PATH . 'log/console/');

// 加载框架引导文件
require './thinkphp/console.php';