#!/usr/bin/env php
<?php
//脚本执行入口
// 定义项目路径


define('APP_PATH', __DIR__ . '/app/');
define('RUNTIME_PATH', __DIR__ . '/data/runtime/');

//define('MODULE', 'install');

// 加载框架引导文件
require './thinkphp/console.php';